name: CI-CD-renv

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    name: Ubuntu Latest (R 4.3.2)

    container:
      image: rocker/geospatial:latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
          use-public-rspm: false
          
      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV
      
      - name: Install renv
        run: |
          R -e 'options(repos = c(CRAN = "https://cloud.r-project.org/")); install.packages("renv")'

      - name: Restore packages
        uses: r-lib/actions/setup-renv@v2

      - name: Deploy to shinyapps.io
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: Rscript deploy/deploy-shinyapps.R
